/**
 * Phase 1 — enquête web : activité, bâtiment, décideur, sources, reco simple.
 */
export const LEAD_GENERATION_GPT_RESEARCH_PHASE1_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    company_name_confirmed: { type: "string" },
    activity_summary: { type: "string" },
    sector: { type: "string", enum: ["industrial", "tertiary", "mixed", "unknown"] },
    building_type: { type: "string", enum: ["industrial", "tertiary", "mixed", "unknown"] },
    height_signal: {
      type: "object",
      additionalProperties: false,
      properties: {
        value: { anyOf: [{ type: "string" }, { type: "null" }] },
        confidence: { type: "string", enum: ["low", "medium", "high"] },
        evidence: { type: "string" },
      },
      required: ["value", "confidence", "evidence"],
    },
    surface_signal: {
      type: "object",
      additionalProperties: false,
      properties: {
        value: { anyOf: [{ type: "string" }, { type: "null" }] },
        confidence: { type: "string", enum: ["low", "medium", "high"] },
        evidence: { type: "string" },
      },
      required: ["value", "confidence", "evidence"],
    },
    heating_signals: { type: "array", items: { type: "string" } },
    qualification_signals: { type: "array", items: { type: "string" } },
    decision_maker: {
      type: "object",
      additionalProperties: false,
      properties: {
        name: { type: "string" },
        role: { type: "string" },
        email: { type: "string" },
        phone: { type: "string" },
        source: { type: "string" },
        confidence: { type: "string", enum: ["low", "medium", "high"] },
      },
      required: ["name", "role", "email", "phone", "source", "confidence"],
    },
    pappers_match: {
      type: "object",
      additionalProperties: false,
      properties: {
        match_confidence: { type: "string", enum: ["none", "low", "medium", "high"] },
        siren: { type: "string" },
        siret: { type: "string" },
        legal_name: { type: "string" },
        head_office_address: { type: "string" },
        legal_form: { type: "string" },
        directors: { type: "array", items: { type: "string" } },
        useful_company_data: { type: "array", items: { type: "string" } },
      },
      required: [
        "match_confidence",
        "siren",
        "siret",
        "legal_name",
        "head_office_address",
        "legal_form",
        "directors",
        "useful_company_data",
      ],
    },
    useful_links: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          url: { type: "string" },
          label: { type: "string" },
        },
        required: ["url", "label"],
      },
    },
    sources: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          url: { type: "string" },
          title: { type: "string" },
          note: { type: "string" },
        },
        required: ["url", "title", "note"],
      },
    },
    qualification_recommendation: { type: "string", enum: ["good", "review", "out_of_target"] },
    qualification_reason: { type: "string" },
  },
  required: [
    "company_name_confirmed",
    "activity_summary",
    "sector",
    "building_type",
    "height_signal",
    "surface_signal",
    "heating_signals",
    "qualification_signals",
    "decision_maker",
    "pappers_match",
    "useful_links",
    "sources",
    "qualification_recommendation",
    "qualification_reason",
  ],
} as const;
