import type { StudyComparableInstallation } from "../domain/types";

/** Références types pour la planche « Installations comparables » des PDF étude / présentation. */
export const STUDY_INSTALLATION_EXAMPLES: StudyComparableInstallation[] = [
  {
    id: "ehpad-1",
    title: "EHPAD — chambres et espaces communs",
    siteType: "Santé / médico-social",
    surfaceM2: 4200,
    heightM: 7.5,
    heatingMode: "Gaz",
    measuredResult: "Confort thermique homogène en chambres et circulations",
    savingEuroYear: 28500,
    invoiceDropPercent: 27,
    installationDurationDays: 2,
    photoUrl: null,
    badge: "Résultat mesuré",
  },
  {
    id: "hotel-1",
    title: "Hôtel — halls, restaurant et étages",
    siteType: "Hébergement hôtelier",
    surfaceM2: 5200,
    heightM: 9,
    heatingMode: "Gaz",
    measuredResult: "Réduction de la stratification dans les volumes hauts",
    savingEuroYear: 35200,
    invoiceDropPercent: 29,
    installationDurationDays: 3,
    photoUrl: null,
    badge: "Résultat mesuré",
  },
  {
    id: "residence-1",
    title: "Résidence de logements collectifs",
    siteType: "Habitation / résidentiel collectif",
    surfaceM2: 3800,
    heightM: 8.5,
    heatingMode: "Gaz",
    measuredResult: "Équilibre des températures entre étages",
    savingEuroYear: 22100,
    invoiceDropPercent: 26,
    installationDurationDays: 2,
    photoUrl: null,
    badge: "Résultat mesuré",
  },
];
