import type { StudyComparableInstallation } from "../domain/types";

export const STUDY_INSTALLATION_EXAMPLES: StudyComparableInstallation[] = [
  {
    id: "indus-1",
    title: "Plateforme logistique multi-cellules",
    siteType: "Site industriel / logistique",
    surfaceM2: 6800,
    heightM: 10.5,
    heatingMode: "Gaz",
    measuredResult: "Température homogénéisée entre 18 et 20°C",
    savingEuroYear: 46100,
    invoiceDropPercent: 31,
    installationDurationDays: 3,
    photoUrl: null,
    badge: "Résultat mesuré",
  },
  {
    id: "tertiaire-1",
    title: "Atelier de production agroalimentaire",
    siteType: "Tertiaire",
    surfaceM2: 3400,
    heightM: 8.2,
    heatingMode: "Gaz",
    measuredResult: "Confort renforcé en zone opérateurs",
    savingEuroYear: 23800,
    invoiceDropPercent: 28,
    installationDurationDays: 2,
    photoUrl: null,
    badge: "Résultat mesuré",
  },
  {
    id: "collectivite-1",
    title: "Centre technique municipal",
    siteType: "Collectivité",
    surfaceM2: 2100,
    heightM: 7.4,
    heatingMode: "Fioul",
    measuredResult: "Baisse des cycles de chauffe observée",
    savingEuroYear: 11900,
    invoiceDropPercent: 24,
    installationDurationDays: 2,
    photoUrl: null,
    badge: "Résultat mesuré",
  },
];
