import { isoToDateInput } from "@/features/operations/lib/datetime";
import { parseRowCeeInputValues } from "@/features/operations/lib/operation-cee-enrich";
import type { OperationInsertInput } from "@/features/operations/schemas/operation.schema";
import type { OperationRow } from "@/features/operations/types";

export const EMPTY_OPERATION_FORM: OperationInsertInput = {
  operation_reference: "",
  beneficiary_id: "",
  lead_id: undefined,
  reference_technical_visit_id: undefined,
  cee_sheet_id: null,
  cee_input_values: {},
  cee_kwhc_calculated: undefined,
  cee_sheet_code: "",
  title: undefined,
  operation_status: "draft",
  sales_status: "draft",
  admin_status: "pending",
  technical_status: "pending",
  delegator_id: undefined,
  sales_owner_id: undefined,
  confirmer_id: undefined,
  admin_owner_id: undefined,
  technical_owner_id: undefined,
  technical_visit_date: undefined,
  quote_sent_at: undefined,
  quote_signed_at: undefined,
  installation_start_at: undefined,
  installation_end_at: undefined,
  deposit_date: undefined,
  prime_paid_at: undefined,
  estimated_quote_amount_ht: undefined,
  estimated_prime_amount: undefined,
  estimated_remaining_cost: undefined,
  valuation_amount: undefined,
  drive_url: undefined,
  signature_url: undefined,
  public_tracking_url: undefined,
  risk_level: undefined,
  notes: undefined,
};

export function operationRowToFormValues(row: OperationRow): OperationInsertInput {
  return {
    operation_reference: row.operation_reference,
    beneficiary_id: row.beneficiary_id,
    lead_id: row.lead_id ?? undefined,
    reference_technical_visit_id: row.reference_technical_visit_id ?? undefined,
    cee_sheet_id: row.cee_sheet_id ?? null,
    cee_input_values: parseRowCeeInputValues(row.cee_input_values),
    cee_kwhc_calculated: row.cee_kwhc_calculated ?? undefined,
    cee_sheet_code: row.cee_sheet_code,
    title: undefined,
    operation_status: row.operation_status,
    sales_status: row.sales_status,
    admin_status: row.admin_status,
    technical_status: row.technical_status,
    delegator_id: row.delegator_id ?? undefined,
    sales_owner_id: row.sales_owner_id ?? undefined,
    confirmer_id: row.confirmer_id ?? undefined,
    admin_owner_id: row.admin_owner_id ?? undefined,
    technical_owner_id: row.technical_owner_id ?? undefined,
    technical_visit_date: isoToDateInput(row.technical_visit_date),
    quote_sent_at: isoToDateInput(row.quote_sent_at),
    quote_signed_at: isoToDateInput(row.quote_signed_at),
    installation_start_at: isoToDateInput(row.installation_start_at),
    installation_end_at: isoToDateInput(row.installation_end_at),
    deposit_date: isoToDateInput(row.deposit_date),
    prime_paid_at: isoToDateInput(row.prime_paid_at),
    estimated_quote_amount_ht: row.estimated_quote_amount_ht ?? undefined,
    estimated_prime_amount: row.estimated_prime_amount ?? undefined,
    estimated_remaining_cost: row.estimated_remaining_cost ?? undefined,
    valuation_amount: row.valuation_amount ?? undefined,
    drive_url: row.drive_url ?? undefined,
    signature_url: row.signature_url ?? undefined,
    public_tracking_url: row.public_tracking_url ?? undefined,
    risk_level: row.risk_level ?? undefined,
    notes: row.notes ?? undefined,
  };
}
