-- ============================================
-- Migration: Créer catégorie Aérotherme électrique et produits
-- Date: 2026-01-07
-- Description: Ajoute la catégorie Aérotherme électrique (grande catégorie: chauffer)
--              et tous les produits d'aérothermes électriques
-- ============================================

-- Créer la catégorie Aérotherme électrique
INSERT INTO public.categories (
  nom,
  slug,
  description,
  description_longue,
  ordre,
  actif,
  images,
  mega_categorie,
  created_at
) VALUES (
  'Aérotherme électrique',
  'aerotherme-electrique',
  'Gamme complète d''aérothermes électriques pour le chauffage des locaux industriels, tertiaires et logistiques. Solutions murales, suspendues et mobiles.',
  'Nos aérothermes électriques permettent de chauffer rapidement et efficacement les ateliers, entrepôts, garages, locaux techniques et zones de stockage. Ils offrent une montée en température rapide, une installation simple (murale, suspendue ou mobile) et une régulation précise pour optimiser le confort et la consommation énergétique.

**Pourquoi choisir nos aérothermes électriques ?**

✅ **Montée en température rapide** : Chauffage efficace des grands volumes
✅ **Installation simple** : Mural, suspendu ou mobile selon vos besoins
✅ **Régulation précise** : Thermostats intégrés pour un contrôle optimal
✅ **Robustesse** : Conçus pour les environnements industriels exigeants
✅ **Économies d''énergie** : Solutions performantes pour réduire vos coûts de chauffage
✅ **Conformité** : Modèles conformes APSAD pour locaux à risque d''incendie

Idéal pour : Ateliers, entrepôts, garages, locaux techniques, zones de stockage, industries navales, environnements humides et corrosifs.',
  11,
  true,
  '[]'::jsonb,
  'chauffer',
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  nom = EXCLUDED.nom,
  description = EXCLUDED.description,
  description_longue = EXCLUDED.description_longue,
  images = EXCLUDED.images,
  mega_categorie = EXCLUDED.mega_categorie;

-- Insérer tous les produits d'aérothermes électriques
INSERT INTO public.products (
  nom,
  slug,
  categorie,
  categorie_id,
  description,
  marque,
  reference,
  prix,
  sur_devis,
  prime_cee,
  actif,
  ordre
) VALUES
-- INELCO - Aérothermes DANIA
('Aérotherme électrique mural fixe DANIA 3,3kW monophasé - SSH3 INELCO',
 'aerotherme-electrique-dania-ssh3-inelco',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural fixe DANIA 3,3kW monophasé. Installation murale simple, idéal pour petits locaux.',
 'INELCO',
 'IN SSH3',
 303.75,
 FALSE,
 FALSE,
 TRUE,
 1),

('Aérotherme électrique mural fixe DANIA 5kW triphasé - SSH5 INELCO',
 'aerotherme-electrique-dania-ssh5-inelco',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural fixe DANIA 5kW triphasé. Puissance adaptée aux locaux moyens.',
 'INELCO',
 'IN SSH5',
 351.00,
 FALSE,
 FALSE,
 TRUE,
 2),

('Aérotherme électrique mural fixe DANIA 9kW triphasé - SSH9 INELCO',
 'aerotherme-electrique-dania-ssh9-inelco',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural fixe DANIA 9kW triphasé. Puissance élevée pour grands volumes.',
 'INELCO',
 'IN SSH9',
 442.50,
 FALSE,
 FALSE,
 TRUE,
 3),

('Aérotherme électrique mural fixe DANIA 15kW triphasé - SSH15 INELCO',
 'aerotherme-electrique-dania-ssh15-inelco',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural fixe DANIA 15kW triphasé. Haute puissance pour très grands volumes.',
 'INELCO',
 'IN SSH15',
 747.00,
 FALSE,
 FALSE,
 TRUE,
 4),

('Aérotherme électrique mural fixe DANIA 22kW triphasé - SSH22 INELCO',
 'aerotherme-electrique-dania-ssh22-inelco',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural fixe DANIA 22kW triphasé. Très haute puissance pour locaux industriels.',
 'INELCO',
 'IN SSH22',
 944.25,
 FALSE,
 FALSE,
 TRUE,
 5),

-- FRICO - Aérothermes CAT
('Aérotherme fixe électrique CAT 3 kW livré avec thermostat TPT16 - C3N FRICO',
 'aerotherme-electrique-cat-c3n-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme fixe électrique CAT 3 kW avec thermostat TPT16 inclus. Solution complète pour petits locaux.',
 'FRICO',
 'FR C3N+TPT16',
 616.85,
 FALSE,
 FALSE,
 TRUE,
 6),

('Aérotherme Fixe Electrique CAT 5 kW livré avec thermostat TPT16-C5N FRICO',
 'aerotherme-electrique-cat-c5n-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme fixe électrique CAT 5 kW avec thermostat TPT16 inclus. Puissance moyenne pour locaux standards.',
 'FRICO',
 'FR C5N+TPT16',
 714.35,
 FALSE,
 FALSE,
 TRUE,
 7),

('Aérotherme Fixe Electrique CAT 9 kW livré avec thermostat TPT16-C9N FRICO',
 'aerotherme-electrique-cat-c9n-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme fixe électrique CAT 9 kW avec thermostat TPT16 inclus. Puissance élevée pour grands volumes.',
 'FRICO',
 'FR C9N+TPT16',
 787.80,
 FALSE,
 FALSE,
 TRUE,
 8),

-- FRICO - Aérothermes PANTHER
('Aérotherme Electrique Triphasé PANTHER FC 6 Suspendu Fixe de 6 kW - PNF06 FRICO',
 'aerotherme-electrique-panther-pnf06-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER FC 6 kW suspendu fixe. Installation suspendue pour optimiser l''espace.',
 'FRICO',
 'FR PNF06',
 878.80,
 FALSE,
 FALSE,
 TRUE,
 9),

('Aérotherme Electrique Triphasé PANTHER FC 9 Suspendu Fixe de 9 kW - PNF09 FRICO',
 'aerotherme-electrique-panther-pnf09-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER FC 9 kW suspendu fixe. Puissance moyenne pour locaux suspendus.',
 'FRICO',
 'FR PNF09',
 946.40,
 FALSE,
 FALSE,
 TRUE,
 10),

('Aérotherme Electrique Triphasé PANTHER FC 12 Suspendu Fixe de 12 kW - PNF12 FRICO',
 'aerotherme-electrique-panther-pnf12-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER FC 12 kW suspendu fixe. Haute puissance suspendue.',
 'FRICO',
 'FR PNF12',
 968.50,
 FALSE,
 FALSE,
 TRUE,
 11),

('Aérotherme électrique triphasé PANTHER T suspendu fixe de 15 kW - FRICO',
 'aerotherme-electrique-panther-pnt15-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER T 15 kW suspendu fixe. Très haute puissance suspendue.',
 'FRICO',
 'FR PNT15',
 1078.70,
 FALSE,
 FALSE,
 TRUE,
 12),

('FAICO Aérotherme Electrique Triphasé PANTHER FC 15 Suspendu Fixe de 15 kW - PNF15 FRICO',
 'aerotherme-electrique-panther-pnf15-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER FC 15 kW suspendu fixe. Haute puissance pour grands volumes suspendus.',
 'FRICO',
 'FR PNF15',
 995.80,
 FALSE,
 FALSE,
 TRUE,
 13),

('FAICO Aérotherme Electrique Triphasé PANTHER T Suspendu Fixe de 20 kW - FRICO',
 'aerotherme-electrique-panther-pnt20-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER T 20 kW suspendu fixe. Très haute puissance suspendue.',
 'FRICO',
 'FR PNT20',
 1269.10,
 FALSE,
 FALSE,
 TRUE,
 14),

('FAICO Aérotherme Electrique Triphasé PANTHER FC 20 Suspendu Fixe de 20 kW - PNF20 FRICO',
 'aerotherme-electrique-panther-pnf20-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER FC 20 kW suspendu fixe. Très haute puissance pour très grands volumes.',
 'FRICO',
 'FR PNF20',
 1171.95,
 FALSE,
 FALSE,
 TRUE,
 15),

('FAICO Aérotherme Electrique Triphasé PANTHER T Suspendu Fixe de 30 kW - FRICO',
 'aerotherme-electrique-panther-pnt30-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER T 30 kW suspendu fixe. Puissance maximale suspendue.',
 'FRICO',
 'FR PNT30',
 1504.30,
 FALSE,
 FALSE,
 TRUE,
 16),

('FAICO Aérotherme Electrique Triphasé PANTHER FC 30 Suspendu Fixe 30 kW - PNF30 FRICO',
 'aerotherme-electrique-panther-pnf30-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé PANTHER FC 30 kW suspendu fixe. Puissance maximale pour très grands volumes.',
 'FRICO',
 'FR PNF30',
 1390.35,
 FALSE,
 FALSE,
 TRUE,
 17),

-- Axelair - Aérothermes ProElec
('Axelair Aérotherme électrique triphasé ProElec AET09 (conforme APSAD) - AXELAIR',
 'aerotherme-electrique-proelec-aet09-axelair',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé ProElec AET09 conforme APSAD. Pour locaux à risque d''incendie.',
 'AXELAIR',
 'AX AET09',
 1008.15,
 FALSE,
 FALSE,
 TRUE,
 18),

('Aérotherme électrique triphasé ProElec AET14 (conforme APSAD) - AXELAIR',
 'aerotherme-electrique-proelec-aet14-axelair',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé ProElec AET14 conforme APSAD. Puissance moyenne pour locaux à risque.',
 'AXELAIR',
 'AX AET14',
 1331.20,
 FALSE,
 FALSE,
 TRUE,
 19),

('Aérotherme électrique triphasé ProElec AET18 (conforme APSAD) - AXELAIR',
 'aerotherme-electrique-proelec-aet18-axelair',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique triphasé ProElec AET18 conforme APSAD. Haute puissance pour locaux à risque.',
 'AXELAIR',
 'AX AET18',
 1762.80,
 FALSE,
 FALSE,
 TRUE,
 20),

-- UNELVENT - Aérothermes EC
('Aérotherme éléctrique mural orientable UNELVENT EC-3N - S&P',
 'aerotherme-electrique-unelvent-ec3n',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural orientable UNELVENT EC-3N. Installation murale avec orientation réglable.',
 'UNELVENT',
 'UN 683242',
 736.06,
 FALSE,
 FALSE,
 TRUE,
 21),

('Aérotherme électrique mural orientable UNELVENT EC-5N - S&P',
 'aerotherme-electrique-unelvent-ec5n',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural orientable UNELVENT EC-5N. Puissance moyenne avec orientation réglable.',
 'UNELVENT',
 'UN 683243',
 1012.43,
 FALSE,
 FALSE,
 TRUE,
 22),

('Aérotherme éléctrique mural orientable UNELVENT EC-9N - S&P',
 'aerotherme-electrique-unelvent-ec9n',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural orientable UNELVENT EC-9N. Puissance élevée avec orientation réglable.',
 'UNELVENT',
 'UN 683244',
 1280.53,
 FALSE,
 FALSE,
 TRUE,
 23),

('Aérotherme électrique mural orientable UNELVENT EC-12N - S&P',
 'aerotherme-electrique-unelvent-ec12n',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural orientable UNELVENT EC-12N. Haute puissance avec orientation réglable.',
 'UNELVENT',
 'UN 683245',
 1600.62,
 FALSE,
 FALSE,
 TRUE,
 24),

('Aérotherme électrique mural orientable UNELVENT EC-15N - S&P',
 'aerotherme-electrique-unelvent-ec15n',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme électrique mural orientable UNELVENT EC-15N. Très haute puissance avec orientation réglable.',
 'UNELVENT',
 'UN 683246',
 1921.78,
 FALSE,
 FALSE,
 TRUE,
 25),

-- OSOVELOR / SOVELOR - Aérothermes
('OSOVELOR Aérotherme aérodestratificateur suspendu électrique AER25 - SOVELOR-DANTHERM',
 'aerotherme-electrique-aer25-sovelor',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme aérodestratificateur suspendu électrique AER25. Combine chauffage et déstratification.',
 'SOVELOR',
 'SO AER25',
 1615.00,
 FALSE,
 FALSE,
 TRUE,
 26),

('OSOVELOR Aérotherme mural TR3D - SOVELOR-DANTHERM',
 'aerotherme-electrique-tr3d-sovelor',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme mural TR3D. Installation murale simple et efficace.',
 'SOVELOR',
 'SO TR3D',
 384.30,
 FALSE,
 FALSE,
 TRUE,
 27),

('OSOVELOR Aérotherme mural TR5D - SOVELOR-DANTHERM',
 'aerotherme-electrique-tr5d-sovelor',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme mural TR5D. Puissance moyenne pour locaux standards.',
 'SOVELOR',
 'SO TR5D',
 497.70,
 FALSE,
 FALSE,
 TRUE,
 28),

('OSOVELOR Aérotherme mural TR9D - SOVELOR-DANTHERM',
 'aerotherme-electrique-tr9d-sovelor',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme mural TR9D. Puissance élevée pour grands volumes.',
 'SOVELOR',
 'SO TR9D',
 603.90,
 FALSE,
 FALSE,
 TRUE,
 29),

('OSOVELOR Aérotherme mural TR15D - SOVELOR-DANTHERM',
 'aerotherme-electrique-tr15d-sovelor',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme mural TR15D. Haute puissance pour très grands volumes.',
 'SOVELOR',
 'SO TR15D',
 926.10,
 FALSE,
 FALSE,
 TRUE,
 30),

-- SOVELOR - Chauffage à air pulsé
('Chauffage à air pulsé suspendu électrique DS15i - SOVELOR-DANTHERM',
 'chauffage-air-pulse-ds15i-sovelor',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Chauffage à air pulsé suspendu électrique DS15i. Solution suspendue pour chauffage rapide.',
 'SOVELOR',
 'SO DS15I',
 608.78,
 FALSE,
 FALSE,
 TRUE,
 31),

-- FRICO - Aérothermes Elektra pour environnements spéciaux
('Aérotherme Elektra ELC331 pour environnement humide et corrosif - FRICO',
 'aerotherme-elektra-elc331-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELC331 pour environnement humide et corrosif. Protection renforcée contre l''humidité et la corrosion.',
 'FRICO',
 'FR ELC331',
 1631.70,
 FALSE,
 FALSE,
 TRUE,
 32),

('Aérotherme Elektra ELC633 pour environnement humide et corrosif - FRICO',
 'aerotherme-elektra-elc633-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELC633 pour environnement humide et corrosif. Puissance moyenne avec protection renforcée.',
 'FRICO',
 'FR ELC633',
 2431.80,
 FALSE,
 FALSE,
 TRUE,
 33),

('Aérotherme Elektra ELC933 pour environnement humide et corrosif - FRICO',
 'aerotherme-elektra-elc933-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELC933 pour environnement humide et corrosif. Puissance élevée avec protection renforcée.',
 'FRICO',
 'FR ELC933',
 2441.60,
 FALSE,
 FALSE,
 TRUE,
 34),

('Aérotherme Elektra ELC1533 pour environnement humide et corrosif - FRICO',
 'aerotherme-elektra-elc1533-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELC1533 pour environnement humide et corrosif. Très haute puissance avec protection renforcée.',
 'FRICO',
 'FR ELC1533',
 2520.70,
 FALSE,
 FALSE,
 TRUE,
 35),

-- FRICO - Aérothermes Elektra pour industrie navale
('Aérotherme Elektra ELV3333 pour l''industrie navale - FRICO',
 'aerotherme-elektra-elv3333-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELV3333 pour l''industrie navale. Conçu pour les environnements marins exigeants.',
 'FRICO',
 'FR ELV3333',
 1668.80,
 FALSE,
 FALSE,
 TRUE,
 36),

('Aérotherme Elektra ELV3344 pour l''industrie navale - FRICO',
 'aerotherme-elektra-elv3344-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELV3344 pour l''industrie navale. Protection marine renforcée.',
 'FRICO',
 'FR ELV3344',
 1668.80,
 FALSE,
 FALSE,
 TRUE,
 37),

('Aérotherme Elektra ELV5333 pour l''industrie navale - FRICO',
 'aerotherme-elektra-elv5333-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELV5333 pour l''industrie navale. Puissance moyenne pour applications navales.',
 'FRICO',
 'FR ELV5333',
 1734.60,
 FALSE,
 FALSE,
 TRUE,
 38),

('Aérotherme Elektra ELV6344 pour l''industrie navale - FRICO',
 'aerotherme-elektra-elv6344-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELV6344 pour l''industrie navale. Haute puissance pour applications navales.',
 'FRICO',
 'FR ELV6344',
 1734.60,
 FALSE,
 FALSE,
 TRUE,
 39),

-- FRICO - Aérothermes Elektra pour locaux haute température
('Aérotherme Elektra ELH633 pour locaux haute température - FRICO',
 'aerotherme-elektra-elh633-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELH633 pour locaux haute température. Conçu pour environnements à température élevée.',
 'FRICO',
 'FR ELH633',
 2226.00,
 FALSE,
 FALSE,
 TRUE,
 40),

('Aérotherme Elektra ELH933 pour locaux haute température - FRICO',
 'aerotherme-elektra-elh933-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme Elektra ELH933 pour locaux haute température. Puissance élevée pour environnements chauds.',
 'FRICO',
 'FR ELH933',
 2284.80,
 FALSE,
 FALSE,
 TRUE,
 41),

-- FRICO - Aérothermes Elektra mobiles pour locaux à risque d'incendie
('Aérotherme mobile Elektra ELF331 pour locaux à risque d''incendie - FRICO',
 'aerotherme-mobile-elektra-elf331-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme mobile Elektra ELF331 pour locaux à risque d''incendie. Mobile et conforme aux normes de sécurité incendie.',
 'FRICO',
 'FR ELF331',
 1461.60,
 FALSE,
 FALSE,
 TRUE,
 42),

('Aérotherme mobile Elektra ELF633 pour locaux à risque d''incendie - FRICO',
 'aerotherme-mobile-elektra-elf633-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme mobile Elektra ELF633 pour locaux à risque d''incendie. Puissance moyenne mobile et sécurisée.',
 'FRICO',
 'FR ELF633',
 1745.10,
 FALSE,
 FALSE,
 TRUE,
 43),

('Aérotherme mobile Elektra ELF933 pour locaux à risque d''incendie - FRICO',
 'aerotherme-mobile-elektra-elf933-frico',
 'aerotherme-electrique',
 (SELECT id FROM public.categories WHERE slug = 'aerotherme-electrique'),
 'Aérotherme mobile Elektra ELF933 pour locaux à risque d''incendie. Haute puissance mobile et sécurisée.',
 'FRICO',
 'FR ELF933',
 2169.30,
 FALSE,
 FALSE,
 TRUE,
 44)

ON CONFLICT (slug) DO UPDATE SET
  nom = EXCLUDED.nom,
  categorie = EXCLUDED.categorie,
  categorie_id = EXCLUDED.categorie_id,
  description = EXCLUDED.description,
  marque = EXCLUDED.marque,
  reference = EXCLUDED.reference,
  prix = EXCLUDED.prix,
  sur_devis = EXCLUDED.sur_devis,
  prime_cee = EXCLUDED.prime_cee,
  actif = EXCLUDED.actif,
  ordre = EXCLUDED.ordre;

-- ============================================
-- Vérification
-- ============================================
SELECT 
  'Catégorie Aérotherme électrique créée' as status,
  COUNT(*) as nombre_produits
FROM public.products
WHERE categorie = 'aerotherme-electrique' AND actif = true;

